theme: osuny
_merge: deep
params:
  plausible: vincentgambardella.com
  summary:
    position: content
  posts:
    index:
      layout: grid
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  debug:
    productionUrl: "https://www.vincentgambardella.com"